export const drugs = {
      drug: [
        {
          drug_name: "Carotid Occlusion",
          intervention_no: "1",
          unk_no: "0",
          drug_code: "CO",
          drug_recdose: "15 sec",
          drug_doserange: "15-30 sec",
          drug_maxdose: "0",
          drug_mindose: "0",
          drug_toxicdose: "0",
          Drug_quantity_eliminated: "",
          drug_actionbp: "1",
          drug_actionhr: "-1",
          drug_type: "Pro",
          changeinbp: "2",
          changeinhr: "2",
          nature: "",
          group: ""
        },
        {
          drug_name: "Central Vagus",
          intervention_no: "2",
          unk_no: "0",
          drug_code: "CV",
          drug_recdose: "15 sec",
          drug_doserange: "15-30 sec",
          drug_maxdose: "0",
          drug_mindose: "0",
          drug_toxicdose: "0",
          Drug_quantity_eliminated: "",
          drug_actionbp: "1",
          drug_actionhr: "1",
          drug_type: "Pro",
          changeinbp: "-2",
          changeinhr: "-2",
          nature: "",
          group: ""
        },
        {
          drug_name: "Peripheral Vagus",
          intervention_no: "3",
          unk_no: "0",
          drug_code: "PV",
          drug_recdose: "15 sec",
          drug_doserange: "15-30 sec",
          drug_maxdose: "0",
          drug_mindose: "0",
          drug_toxicdose: "0",
          Drug_quantity_eliminated: "",
          drug_actionbp: "-1",
          drug_actionhr: "-1",
          drug_type: "Pro",
          changeinbp: "-2",
          changeinhr: "-3",
          nature: "",
          group: ""
        },
        {
          drug_name: "Epinephrine",
          intervention_no: "4",
          unk_no: "1",
          drug_code: "Epi",
          drug_recdose: "2",
          drug_doserange: "1-3",
          drug_maxdose: "10",
          drug_mindose: "0.5",
          drug_toxicdose: "15",
          Drug_quantity_eliminated: "",
          drug_actionbp: "1",
          drug_actionhr: "1",
          drug_type: "Ago",
          changeinbp: "2",
          changeinhr: "-3",
          doseIncrVal: "1",
          nature: "Neutral",
          group: "1"
        },
        {
          drug_name: "Norepinephrine",
          intervention_no: "5",
          unk_no: "2",
          drug_code: "Nepi",
          drug_recdose: "3",
          drug_doserange: "2-5",
          drug_maxdose: "15",
          drug_mindose: "1.25",
          drug_toxicdose: "25",
          Drug_quantity_eliminated: "",
          drug_actionbp: "1",
          drug_actionhr: "-1",
          drug_type: "Ago",
          changeinbp: "3",
          changeinhr: "-3",
          doseIncrVal: "1",
          nature: "Neutral",
          group: "1"
        },
        {
          drug_name: "Isoprenaline",
          intervention_no: "6",
          unk_no: "3",
          drug_code: "Iso",
          drug_recdose: "3",
          drug_doserange: "2-5",
          drug_maxdose: "15",
          drug_mindose: "1.25",
          drug_toxicdose: "25",
          Drug_quantity_eliminated: "",
          drug_actionbp: "-1",
          drug_actionhr: "1",
          drug_type: "Ago",
          changeinbp: "-3",
          changeinhr: "3",
          doseIncrVal: "1",
          nature: "Adrenergic drug",
          group: "2"
        },
        {
          drug_name: "Acetylcholine",
          intervention_no: "7",
          unk_no: "4",
          drug_code: "ACh",
          drug_recdose: "5",
          drug_doserange: "2-10",
          drug_maxdose: "40",
          drug_mindose: "1.25",
          drug_toxicdose: "50",
          Drug_quantity_eliminated: "",
          drug_actionbp: "-1",
          drug_actionhr: "-1",
          drug_type: "Ago",
          changeinbp: "-3",
          changeinhr: "-3",
          doseIncrVal: "1",
          nature: "Adrenergic drug",
          group: "6"
        },
        {
          drug_name: "Histamine",
          intervention_no: "8",
          unk_no: "5",
          drug_code: "Hist",
          drug_recdose: "3",
          drug_doserange: "2-5",
          drug_maxdose: "15",
          drug_mindose: "1.25",
          drug_toxicdose: "25",
          Drug_quantity_eliminated: "",
          drug_actionbp: "-1",
          drug_actionhr: "-1",
          drug_type: "Ago",
          changeinbp: "-3",
          changeinhr: "2",
          doseIncrVal: "1",
          nature: "Adrenergic drug",
          group: "2"
        },
        {
          drug_name: "Ephedrine",
          intervention_no: "9",
          unk_no: "0",
          drug_code: "Ephe",
          drug_recdose: "200",
          drug_doserange: "100 - 200",
          drug_maxdose: "800",
          drug_mindose: "50",
          drug_toxicdose: "1000",
          Drug_quantity_eliminated: "",
          drug_actionbp: "1",
          drug_actionhr: "1",
          drug_type: "Ago",
          changeinbp: "3",
          changeinhr: "2",
          doseIncrVal: "20",
          nature: "Anticholinergic",
          group: "1"
        },
        {
          drug_name: "Phentolamine",
          intervention_no: "10",
          unk_no: "7",
          drug_code: "Phen",
          drug_recdose: "1000",
          drug_doserange: "----",
          drug_maxdose: "2500",
          drug_mindose: "500",
          drug_toxicdose: "3000",
          Drug_quantity_eliminated: "10",
          drug_actionbp: "-1",
          drug_actionhr: "1",
          drug_type: "Ant",
          changeinbp: "-3",
          changeinhr: "2",
          doseIncrVal: "100",
          nature: "Anticholinergic",
          group: "2",
          druglevel:0,
        },
        {
          drug_name: "Propranolol",
          intervention_no: "11",
          unk_no: "8",
          drug_code: "Prop",
          drug_recdose: "1000",
          drug_doserange: "----",
          drug_maxdose: "2500",
          drug_mindose: "500",
          drug_toxicdose: "3000",
          Drug_quantity_eliminated: "10",
          drug_actionbp: "-1",
          drug_actionhr: "-1",
          drug_type: "Ant",
          changeinbp: "-3",
          changeinhr: "-2",
          doseIncrVal: "100",
          nature: "Anticholinergic",
          group: "3",
          druglevel:0,
        },
        {
          drug_name: "Atropine",
          intervention_no: "12",
          unk_no: "9",
          drug_code: "Atro",
          drug_recdose: "750",
          drug_doserange: "500 - 1000",
          drug_maxdose: "4000",
          drug_mindose: "250",
          drug_toxicdose: "5000",
          Drug_quantity_eliminated: "10",
          drug_actionbp: "0",
          drug_actionhr: "0",
          drug_type: "Ant",
          changeinbp: "0",
          changeinhr: "2",
          doseIncrVal: "100",
          nature: "Cholinergic drugs",
          group: "4",
          druglevel:0,
        },
        {
          drug_name: "Mepyramine",
          intervention_no: "13",
          unk_no: "10",
          drug_code: "Mepy",
          drug_recdose: "5000",
          drug_doserange: "----",
          drug_maxdose: "0",
          drug_mindose: "2500",
          drug_toxicdose: "0",
          Drug_quantity_eliminated: "10",
          drug_actionbp: "0",
          drug_actionhr: "0",
          drug_type: "Ant",
          changeinbp: "0",
          changeinhr: "0",
          doseIncrVal: "100",
          nature: "Cholinergic drugs",
          group: "5",
          druglevel:0,
        },
        {
          drug_name: "Cimetidine",
          intervention_no: "14",
          unk_no: "11",
          drug_code: "Cime",
          drug_recdose: "5000",
          drug_doserange: "----",
          drug_maxdose: "0",
          drug_mindose: "2500",
          drug_toxicdose: "0",
          Drug_quantity_eliminated: "10",
          drug_actionbp: "0",
          drug_actionhr: "0",
          drug_type: "Ant",
          changeinbp: "0",
          changeinhr: "0",
          doseIncrVal: "100",
          nature: "Cholinergic drugs",
          group: "5",
          druglevel:0,
        }
      ]
    }
  